# Generated by Django 5.0.2 on 2024-03-21 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=0, max_length=255, null=0)),
                ('imagen', models.ImageField(null=1, upload_to='imagenes/asignaturas')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Duda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=0, null=0)),
                ('estado', models.CharField(blank=0, default='enviado', max_length=25, null=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Duda',
                'verbose_name_plural': 'Dudas',
                'db_table': 'duda',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ActividadEvaluativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=0)),
                ('objetivo_evaluar', models.CharField(blank=0, max_length=255, null=0)),
                ('orden', models.TextField(blank=0, null=0)),
                ('fecha_cierre', models.DateTimeField(blank=0, null=0)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.asignatura')),
            ],
            options={
                'verbose_name': 'ActividadEvaluativa',
                'verbose_name_plural': 'ActividadesEvaluativas',
                'db_table': 'actividad_evaluativa',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=0)),
                ('encabezado', models.CharField(blank=0, max_length=255, null=0)),
                ('cuerpo', models.TextField(blank=0, null=0)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.asignatura')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eva.usuario')),
                ('grupo', models.CharField(blank=0, max_length=10, null=0)),
                ('grado', models.PositiveIntegerField(blank=0, null=0)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
            bases=('eva.usuario',),
        ),
        migrations.CreateModel(
            name='RespuestaDuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=0, null=0)),
                ('estado', models.CharField(blank=0, default='enviado', max_length=20, null=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('duda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eva.duda')),
            ],
            options={
                'verbose_name': 'Respuesta_Duda',
                'verbose_name_plural': 'Respuesta_Dudas',
                'db_table': 'respuesta_duda',
            },
        ),
        migrations.CreateModel(
            name='RespuestaActividadEvaluativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=1, null=1)),
                ('estado', models.CharField(default='pendiente', max_length=25)),
                ('resuelta', models.BooleanField(default=0)),
                ('calificacion', models.FloatField(blank=1, null=1)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.actividadevaluativa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.estudiante')),
            ],
            options={
                'verbose_name': 'RespuestaActividadEvaluativa',
                'verbose_name_plural': 'RespuestasActividadEvaluativa',
                'db_table': 'respuesta_actividad_evaluativa',
            },
        ),
        migrations.AddField(
            model_name='duda',
            name='estudiante',
            field=models.ForeignKey(blank=0, null=0, on_delete=django.db.models.deletion.CASCADE, to='eva.estudiante'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='estudiantes',
            field=models.ManyToManyField(blank=1, null=1, to='eva.estudiante'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eva.usuario')),
                ('asignatura', models.ForeignKey(default=None, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='eva.asignatura')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesor',
            },
            bases=('eva.usuario',),
        ),
        migrations.AddField(
            model_name='duda',
            name='profesor',
            field=models.ForeignKey(blank=0, null=0, on_delete=django.db.models.deletion.CASCADE, to='eva.profesor'),
        ),
    ]
