# Generated by Django 5.0.2 on 2024-03-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadevaluativa',
            name='objetivo_evaluar',
        ),
        migrations.AddField(
            model_name='actividadevaluativa',
            name='objetivoEvaluar',
            field=models.CharField(blank=0, default=1, max_length=255, null=0),
            preserve_default=False,
        ),
    ]
