# Generated by Django 5.0.2 on 2024-03-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0004_alter_clase_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadevaluativa',
            options={'verbose_name': 'ActividadEvaluativa', 'verbose_name_plural': 'ActividadesEvaluativas'},
        ),
        migrations.AlterUniqueTogether(
            name='actividadevaluativa',
            unique_together={('asignatura', 'numero')},
        ),
    ]
