# Generated by Django 5.0.2 on 2024-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0006_remove_actividadevaluativa_fecha_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadevaluativa',
            name='habilitada',
        ),
        migrations.AddField(
            model_name='actividadevaluativa',
            name='estado',
            field=models.CharField(choices=[('Deshabilitada', 'Deshabilitada'), ('Habilitada', 'Habilitada')], default='Deshabilitada', max_length=50),
        ),
    ]
