# Generated by Django 5.0.2 on 2024-04-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0009_remove_respuestaactividadevaluativa_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuestaactividadevaluativa',
            unique_together={('actividad', 'estudiante')},
        ),
    ]
