# Generated by Django 5.0.2 on 2024-04-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0010_alter_respuestaactividadevaluativa_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='duda',
            name='sobre',
            field=models.CharField(blank=0, default=1, max_length=255, null=0),
            preserve_default=False,
        ),
    ]
