# Generated by Django 5.0.2 on 2024-04-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0011_duda_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duda',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
