# Generated by Django 5.0.2 on 2024-04-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0013_remove_duda_estado_duda_visto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaduda',
            name='estado',
        ),
        migrations.AddField(
            model_name='respuestaduda',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
