# Generated by Django 5.0.2 on 2024-04-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0014_remove_respuestaduda_estado_respuestaduda_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaduda',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
