# Generated by Django 5.0.2 on 2024-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0015_alter_respuestaduda_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaduda',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
    ]
